### ISSUE TITLE
Generated SQL

### ISSUE THREAD

**Issue by mattbretl** [graphile-contrib/pg-many-to-many#1]
Without this plugin, queries on many-to-many relations look like this:

```graphql
{
  allPeople {
    nodes {
      teamMembersByPersonId {
        nodes {
          teamByTeamId {
            teamName
          }
        }
      }
    }
  }
}
```

and generate the following SQL fragment:

```sql
-- ... snip
select to_json(
  (
    json_build_object(
      '@teamByTeamId'::text,
      (
        select json_build_object(
          'teamName'::text,
          (__local_2__."team_name")
        ) as object
        from "public"."team" as __local_2__
        where (__local_3__."team_id" = __local_2__."id") and (TRUE) and (TRUE)
      )
    )
  )
) as "@nodes"
from "public"."team_member" as __local_3__
where (__local_3__."person_id" = __local_4__."id") and (TRUE) and (TRUE)
order by __local_3__."person_id" ASC,
__local_3__."team_id" ASC
-- ... snip
```

With this plugin, queries look like this:

```graphql
{
  allPeople {
    nodes {
      teamsByTeamMemberPersonIdAndTeamId {
        nodes {
          teamName
        }
      }
    }
  }
}
```

and generate the following SQL fragment:

```sql
-- ...
select to_json(
  (
    json_build_object(
      'teamName'::text,
      (__local_2__."team_name")
    )
  )
) as "@nodes"
from "public"."team" as __local_2__
where (
  __local_2__."id" in (
    select "team_id"
    from "public"."team_member"
    where "person_id" = __local_3__."id"
  )
) and (TRUE) and (TRUE)
order by __local_2__."id" ASC
-- ...
```

@benjie - Can we / should we try to do better? I tried adding `team_member` as a second table after `from "public"."team" as __local_2__`, but kept getting an error that `from` was locked. Obviously we don't have `join` support yet either. Thoughts?

**Comment by benjie** [comment]
We're not going to use joins for any non-singular relations. My guess is that for deep queries (5+ levels) they'll result in orders of magnitude more data being sent between server and database, increased memory usage, increasing latency, and increasing garbage collection overhead. Subqueries are fine for this, IMO.

What would a better solution look like to you?

**Comment by mattbretl** [comment]
I was referring to a SQL join, not joining in JS.

I would have done this:

```sql
inner join "public"."team_member" as __local_X__ on
  __local_X__."team_id" = __local_2__."id"
    and
  __local_X__."person_id" = __local_3__."id"
```

instead of using a subquery in a where clause. But I don't see anything wrong with the subquery.

**Comment by benjie** [comment]
So was I; e.g. if you run this script you'll see that the amount of data returned for the query with joins is much higher than the one with subqueries. This is only a simple query with a small dataset and only 3 levels deep; you can imagine as it got bigger and more columns were requested it would get exponentially worse.

```sql
drop schema if exists joins cascade;
create schema joins;
set search_path to joins;

create table a (
  a_id serial primary key,
  name text not null,
  bio text not null default('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.')
);

create table b (
  b_id serial primary key,
  location text not null
);

create table c (
  c_id serial primary key,
  status text not null
);

create table a_b (
  a_id int not null references a,
  b_id int not null references b
);

create table b_c (
  b_id int not null references b,
  c_id int not null references c
);

insert into a(name) values ('Alice'), ('Bob'), ('Caroline'), ('David');
insert into b(location) values ('Here'), ('There'), ('Everywhere'), ('Nowhere');
insert into c(status) values ('PENDING'), ('IN_PROGRESS'), ('FINALISING'), ('COMPLETED');
insert into a_b select a_id, b_id from a, b;
insert into b_c select b_id, c_id from b, c;

select a_id, name, bio, b_id, location, c_id, status from a inner join a_b using (a_id) inner join b using (b_id) inner join b_c using (b_id) inner join c using (c_id);

select a_id, name, bio, (
  select json_agg(
    json_build_object('b_id', b_id, 'location', location, 'statuses', (
      select json_agg(
        json_build_object('c_id', c_id, 'status', status)
      )
      from c
      where exists(select 1 from b_c where b_c.b_id = b.b_id)
    ))
  )
  from b
  where exists(select 1 from a_b where a_b.a_id = a.a_id)
) bs from a;
```

**Comment by mattbretl** [comment]
I definitely agree with keeping the json_agg/json_build_object in PG. The join I suggested only replaces the where clause, and wouldn't modify the result set in any way.

Here's the join syntax with your schema:
```sql
set search_path to joins;
select a_id, name, bio, (
  select json_agg(
    json_build_object('b_id', b.b_id, 'location', location, 'statuses', (
      select json_agg(
        json_build_object('c_id', c.c_id, 'status', status)
      )
      from c
      --where exists(select 1 from b_c where b_c.b_id = b.b_id)
        inner join b_c on b_c.b_id = b.b_id
    ))
  )
  from b
  --where exists(select 1 from a_b where a_b.a_id = a.a_id)
    inner join a_b on a_b.a_id = a.a_id
) bs from a;
```

It does the same thing.. returns four rows of complex JSON objects.

I'm totally fine keeping the subqueries.. just wanted to run it by you.

**Comment by benjie** [comment]
Ah I see. The only slight issue there is that these return different results; e.g. yours can return duplicates where mine cannot. If you expose the join table records on edges then your way is better; if you don't then I think mine is. There's a risk if I add join functionality without a load of caveats that it will be abused for non one-to-one joins, resulting in bugs and more support overhead for me; I think the exists subquery is probably similarly performant to the join?

**Comment by mattbretl** [comment]
You're right.. I forgot about the join duplication that might occur if the foreign key columns don't have unique constraints. That's trivial to protect against within the plugin, but like you said, the existing subquery works, so let's just leave it.

I'll close this and we can revisit if/when #2 becomes a concern.
