### ISSUE TITLE
Comment on foreign key constraint ignored for simple collections

### ISSUE THREAD

**Issue by marton78** [graphile-contrib/pg-many-to-many#10]
Hi,

thanks for this very useful plugin! While testing, I realised that while adding a comment on a foreign key constraint works great with PostGraphile's default setting`--simple-collections omit`, the comment is ignored when PostGraphile is invoked with `--simple-collections only`.

**Comment by marton78** [comment]
Never mind, I found the solution. I suggest making the usage more explicit in the example at the bottom of README.md:

```
comment on constraint team_member_team_id_fkey on p.team_member is E'@manyToManyFieldName teams\n@manyToManySimpleFieldName teamsList';
```

**Comment by benjie** [comment]
@marton78 Please feel free to submit a PR with improved wording; you can do so without leaving the GitHub web interface:

https://github.com/graphile-contrib/pg-many-to-many/edit/master/README.md

**Comment by mattbretl** [comment]
@marton78 Thanks for the feedback. I went ahead and added your example to the README.
