### ISSUE TITLE
Support @simpleCollections smart comments on the foreign key

### ISSUE THREAD

**Issue by gbesacier** [graphile-contrib/pg-many-to-many#12]
Currently, only the global --simple-collections flag is supported. As you are already checking the tags on the foreign key (for @manyToManyFieldName and @manyToManySimpleFieldName), you could also probably check @simpleCollections to override the global flag on a case by case basis.

**Comment by mattbretl** [comment]
Thanks for the suggestion. This is now supported in 1.0.0-beta.6.
