### ISSUE TITLE
Support for many to many relationships of the same type?

### ISSUE THREAD

**Issue by owmawila** [graphile-contrib/pg-many-to-many#15]
Support for many to many relationships of the same type? The plugin doesn't seem to handle this currently unless I'm missing something?

**Comment by mattbretl** [comment]
Confirmed, thanks for reporting this. Here's the culprit: https://github.com/graphile-contrib/pg-many-to-many/blob/26fce3e4c1c8899cd1f1c62e55d63d91ca2d45ff/src/PgManyToManyRelationPlugin.js#L104

I want to fix this, but I need to give a little thought to the logic and add some tests before ripping out that check; probably won't happen until next week.

**Comment by mattbretl** [comment]
This is fixed in 1.0.0-beta.10
