### ISSUE TITLE
Expose junction table columns as fields on edges

### ISSUE THREAD

**Issue by mattbretl** [graphile-contrib/pg-many-to-many#2]

**Comment by benjie** [comment]
This is very much a stretch goal. If you do this, you need to use a different connection type (not the standard table one), resulting in two new connection types per many-many relationship (one for each direction).

**Comment by tinymarsracing** [comment]
Hey there, just to be clear, this issue is for the case where we can do this without the plugin:
```gql
{
  shop(name: "Amazon") {
    shopProducts {
      nodes {
        price
        product {
          EAN
        }
      }
    }
  }
}
```
And we would prefer to be able to do this using the plugin:
```gql
{
  shop(name: "Amazon") {
    products {
      nodes {
        EAN
        price
      }
    }
  }
}
```
Correct?

I was adapting the [computed column method](https://github.com/graphile/postgraphile/issues/91#issuecomment-308664225) a bit and got this:
```sql
create table shops (
  name text primary key
);

create table products (
  ean ean primary key
);

create table shop_products (
  shop text references shops,
  ean ean references products,
  price price
);

create table products_extended (
  price price
) inherits (products);

create function shops_products(s shops)
returns setof products_extended as $$
  select products.*, shop_products.price
  from products
  inner join shop_products
  on (shop_products.ean = products.ean)
  where shop_products.shop = s.name;
$$ language sql stable;
```

This works, but I would prefer a more automatic way. I guess I could probably create a re-usable function that does that. So, my extended table is exactly the "different connection type" Benjie was talking about, right? The easiest solution is probably to just stick with the non-plugin way from the beginning.

**Comment by tinymarsracing** [comment]
Btw, I realized that table inheritance might be a bad idea here. It causes the `products_extended` table to be accessed as well whenever querying the `products` table. When noticing this I realized that using table inheritance like this is probably a hack with who knows what other consequences. Not sure how to extend the composite type directly though, so one might have to create a new one from scratch with all the table's fields...

**Comment by benjie** [comment]
That's not exactly the intent here; rather than adding to the _nodes_ we were considering adding to the _edges_.

So, for example, if you have:

```sql
create table shops(
  id serial primary key,
  name text not null
);
create table products(
  id serial primary key,
  name text not null
);
create table shop_products (
  shop_id int references shops,
  product_id int references products,
  price_in_cents int not null
);
```

then we want to be able to query:

```graphql
{
  shopById(id: 2) {
    id
    name
    products {
      edges {
        node { id name }
        priceInCents
      }
    }
  }
}
```

Since the connection is specific to the relationship between the shop and the products, and it has metadata on the junction table (in this case the metadata is `price_in_cents`), we could potentially expose the metadata via the connection's edges. Effectively this metadata would be a property of the edge in the graph representation, so this makes total sense. But from a practicality POV it may result in an explosion of types, see above.

**Comment by tinymarsracing** [comment]
Maybe I don't understand the difference between `nodes` and `edges` enough. I thought `nodes` is just a "simpler" way to expose the `edges` (with less pagination options).

So, to use your edges example, what I want is that:
```gql
{
  shopById(id: 2) {
    id
    name
    products {
      edges {
        node { id name }
        
      }
    }
  }
}
```

**Comment by tinymarsracing** [comment]
Maybe I don't understand the difference between `nodes` and `edges` enough. I thought `nodes` is just a "simpler" way to expose the `edges` (with less pagination options).

So, to use your `edges` example, what I want is that:
```gql
{
  shopById(id: 2) {
    id
    name
    products {
      edges {
        node {
          id
          name
          priceInCents
        } 
      }
    }
  }
}
```

Or in (in my understanding) the reduced equivalent `nodes` syntax:
```gql
{
  shopById(id: 2) {
    id
    name
    products {
      nodes {
        id
        name
        priceInCents 
      }
    }
  }
}
```

So, this is query is also not possible with the plugin at the moment, right?

**Comment by benjie** [comment]
In a graph you can have a connection `A ---> B`. `A` and `B` are "Nodes". For the example, `A` is a node of type "Shop" and `B` is a node of type "Product". `B` has lots of other things pointing at it (other shops, and more).

When you're at `B`, you don't know which way you got there from, so it cannot have any "contextual" information about how you got there - `B`'s properties are fixed. For the `priceInCents` in the example, the `priceInCents` is not a property of `A`, and it's not a property of `B`, instead it's part of the link between `A` and `B`, it's part of the arrow `--->` itself. This arrow is called an "edge". An edge defines where it comes from (`A`), where it goes to (`B`), and any additional data that relates to this relationship.

In PostGraphile, `nodes` in a connection is a shortcut to give you a list of the nodes (all the `B`s) associated with a connection, ignoring any data on their edges (currently just the `cursor`).

Put another way, the Product itself does not have one single `priceInCents`, it has different prices in different shops. This is thus not a property of the `Product` node, and if we were to treat it as such we would break a lot of the graph model (which would be surfaced as things like invalid cache updates).

**Comment by tinymarsracing** [comment]
Oh, I get it, that last part is what I was missing. I realize now how different `edges` and `nodes` are in that example. So, exposing the edge field as part of the `product` (which is also what my function does) might seem like a nice way to make *one* query look more document like (and thereby making it more straight forward to people unfamiliar with SQL). However, if it gets cached with the `nodeId` of the `product` then every `shop` always has the `price` of the last queried `shopProduct` as its `price` in the cache. But if as you say this breaks the graph model, doesn't a NoSQL database also break the graph model when it denormalizes the data to the `shop` just like I kind of want to do with my function? :smile: (I guess in that case every "shopProduct" would at least have a different nodeId that might be more tricky to do with Postgres.)

Anyway, thank you for the explanation! I think I'm just gonna use the original non-plugin way for now, maybe renaming the junction table relation from `shopProducts` to `products`. This already makes it look a bit more document like.

**Comment by tinymarsracing** [comment]
PS: I just realized something. Many people are always saying that GraphQL is a query language and has nothing to do with graph databases. But that's not true, right? If an edge stores information about the relation between nodes, that sounds a lot like a graph database. :smile:

**Comment by benjie** [comment]
It’s like a graph; not necessarily a graph database.
