### ISSUE TITLE
Support renaming fields with smart comments

### ISSUE THREAD

**Issue by mattbretl** [graphile-contrib/pg-many-to-many#3]

**Comment by gcoda** [comment]
i am not really sure what i am doing, but it works in my case
what do you think about [this](https://github.com/gcoda/pg-many-to-many/commit/44e98aa27e31b71c6f5d4fdc373a29c21c3a2d2f)?

**Comment by benjie** [comment]
That should be reserved for defining manyToMany; maybe manyToManyName?

**Comment by gcoda** [comment]
Makes sense. 
There is `resultFieldName` and `foreignFieldName`, maybe it should end with `FieldName` too?

`hasManyFieldName` ?

**Comment by mattbretl** [comment]
I agree that it should end with `FieldName`. I also think the comment should go on the constraint (instead of the column), similar to how one-to-many relations are implemented:

```sql
comment on constraint team_member_team_id_fkey
on p.team_member is E'@manyToManyFieldName teams';
```

This is now available in beta.3.
