### ISSUE TITLE
@omit read on tables

### ISSUE THREAD

**Issue by ab-pm** [graphile-contrib/pg-many-to-many#44]
Like the builtin `PgForwardRelation` and `PgBackwardRelation` plugins, the many-to-many relation plugin should consider `omit` smart tags on the tables themselves. I have a problem with this as I wanted to completely `@omit` a table of my database, but pg-many-to-many still created a field referencing the type.

To be more specific, I think there should be a `omit(junctionTable, "read")` check in [line 32](https://github.com/graphile-contrib/pg-many-to-many/blob/fbfbf2ba0565b611ecadb062401bc83fe41d2276/src/manyToManyRelationships.js#L32) and a `omit(rightTable, "read")` check around [line 65](https://github.com/graphile-contrib/pg-many-to-many/blob/fbfbf2ba0565b611ecadb062401bc83fe41d2276/src/manyToManyRelationships.js#L65).

**Comment by mattbretl** [comment]
Apologies for the ridiculously long delay in fixing this. I've included in the fix in version 1.0.0.

**Comment by ab-pm** [comment]
@mattbretl Thanks for working on this, but that `omit(rightTable, "manyToMany")` is kinda unexpected - I think the `manyToMany` should only be considered on the junction table and on the constraints.

**Comment by bjorkegeek** [comment]
> @mattbretl Thanks for working on this, but that `omit(rightTable, "manyToMany")` is kinda unexpected - I think the `manyToMany` should only be considered on the junction table and on the constraints.

It bit me. I have a setup where I automatically tagged all my non-junction tables as `omit manyToMany`. Ooops, no more many-to-many relations after upgrade. My solution was to tag all foreign key constraints of all non-junction tables instead. But it could be convenient to have a way of preventing a table from being considered a junction table without disqualifying it from many-to-many relations completely.
