### ISSUE TITLE
Exposing Edge properties in "Simple Collections"

### ISSUE THREAD

**Issue by PaulMcMillan** [graphile-contrib/pg-many-to-many#52]
This is a continuation of #19 - I'd love a way to expose edge properties when I'm using Simple Collections. I'm not 100% sure there's a way to do this cleanly in GraphQL, but I was thinking of exposing it as something like an "incoming_edge" connection or something similar.

Today in our application we are exposing both the m2m generated edges, and the built in FK support, since that allows selecting join table columns, but having two ways to do that is confusing to users.

**Comment by benjie** [comment]
The only way to reasonably do this _with simple collections_ would be to add another field _next to_ the collection; by which point you might as well use one-to-many relations.

e.g. assuming you had:

```sql
create table users (id serial primary key, ... );
create table forums (id serial primary key, ... );
create table forum_users(forum_id int references forums, user_id int references users, ...);
```

The sensible GraphQL using only simple collections would be:

```graphql
type Forum {
  members: [User!]
  memberships: [ForumUser!]
}
```

Adding a field to `User` that represents a `ForumUser` based solely on the path through which you found said user would break the caching model of GraphQL on the client, and is not how a "graph" would work.

**Comment by PaulMcMillan** [comment]
I'm convinced, especially after reading more about how the caching usually works. I'll turn back on the edges/nodes in the next iteration.
