### ISSUE TITLE
typescript error

### ISSUE THREAD

**Issue by sasa6277** [graphile-contrib/pg-many-to-many#55]
when i use typescript i get this error:

Could not find a declaration file for module '@graphile-contrib/pg-many-to-many'. '/home/sasa/Public/testProject/blogproject/server/node_modules/@graphile-contrib/pg-many-to-many/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/graphile-contrib__pg-many-to-many` if it exists or add a new declaration (.d.ts) file containing `declare module '@graphile-contrib/pg-many-to-many';

**Comment by benjie** [comment]
Addressed in https://github.com/graphile-contrib/pg-many-to-many/pull/56

**Comment by sasa6277** [comment]
i use 
https://github.com/graphile-contrib/pg-many-to-many#inflector-plugin
and it work

**Comment by sasa6277** [comment]
thank u
