### ISSUE TITLE
Plugin is undefined on initialization

### ISSUE THREAD

**Issue by jfcieslak** [graphile-contrib/pg-many-to-many#64]
## Problem

When starting the server with this plugin added, this error occurs:

**Error: Option 'appendPlugins' should be an array of functions, found 'undefined' at index 0**

The other plugin (SimplifyInflector) loads without issues.

## Reproduction
postgraphile 4.12.4 as an express middleware

instal the plugin with yarn, import it in the project and add to `appendPlugins` array.

Could this be related to to tsconfig settings?

minimal server repro:

``` typescript
import { config } from 'dotenv'
import express = require('express')
import { postgraphile } from 'postgraphile'
import SimplifyInflector from '@graphile-contrib/pg-simplify-inflector'
import PgManyToManyPlugin from '@graphile-contrib/pg-many-to-many'

const app = express()

app.use(
	postgraphile(process.env.POSTGRES_DATABASE_URL, {
		watchPg: true,
		dynamicJson: true,
		setofFunctionsContainNulls: false,
		ignoreRBAC: false,
		ignoreIndexes: false,
		showErrorStack: 'json',
		extendedErrors: ['hint', 'detail', 'errcode'],
		appendPlugins: [PgManyToManyPlugin, SimplifyInflector],
		exportGqlSchemaPath: 'generated/graphql/schema.gql',
		graphiql: true,
		enhanceGraphiql: true,
		enableQueryBatching: true,
		legacyRelations: 'omit',
		allowExplain: () => true,
	})
)

const port = process.env.API_PORT
const server = app.listen(port, () => {
	console.log(`Listening at http://localhost:${port}/graphiql`)
})
server.on('error', console.error)

```

**Comment by benjie** [comment]
Could be; try

```
import * as PgManyToManyPlugin from '@graphile-contrib/pg-many-to-many'
```

**Comment by benjie** [comment]
(I believe the relevant TS setting is something like `esModuleInterop: true`)

**Comment by jfcieslak** [comment]
Thank you for such quick response! Yes, I can confrm this was the setting responsible, setting `esModuleInterop: true` fixed the undefined import. I am a bit curious tho as to what is the difference between this particular export and the other core plugins (such as `@graphile-contrib/pg-simplify-inflector'`) as they seem to work without issues. But anyway, this fixes it.

**Comment by benjie** [comment]
We have a specific workaround for this in pg-simplify-inflector:

https://github.com/graphile/pg-simplify-inflector/blob/main/index.ts#L574
