### ISSUE TITLE
TypeScript type declares a default export, but library doesn't set `modules.export.default`

### ISSUE THREAD

**Issue by lediur** [graphile-contrib/pg-many-to-many#71]
## Issue

When importing this plugin library with:

```ts
import PgManyToManyPlugin from '@graphile-contrib/pg-many-to-many';
```

using the plugin in `createPostGraphileSchema` throws a runtime error:

```
[Error: Option 'appendPlugins' should be an array of functions, found 'undefined' at index 1]
```

## Investigation

The library's `index.d.ts` exports `PgManyToManyPlugin` as a default export, but the library's `index.js` doesn't set `modules.exports.default` to the function. As a result, there seems to be a conflict between the types (expecting a default import) and the runtime behavior (expecting an `import * as`-style import).

Contrast this with https://github.com/graphile/pg-simplify-inflector, where both the types and the library set the default export as expected.

## Workaround

Using patch-package:

```patch
diff --git a/node_modules/@graphile-contrib/pg-many-to-many/index.js b/node_modules/@graphile-contrib/pg-many-to-many/index.js
index 6c28f70..3ab1736 100644
--- a/node_modules/@graphile-contrib/pg-many-to-many/index.js
+++ b/node_modules/@graphile-contrib/pg-many-to-many/index.js
@@ -4,7 +4,7 @@ const PgManyToManyRelationPlugin = require("./src/PgManyToManyRelationPlugin.js"
 const PgManyToManyRelationEdgeColumnsPlugin = require("./src/PgManyToManyRelationEdgeColumnsPlugin.js");
 const PgManyToManyRelationEdgeTablePlugin = require("./src/PgManyToManyRelationEdgeTablePlugin.js");
 
-module.exports = function PgManyToManyPlugin(builder, options) {
+function PgManyToManyPlugin(builder, options) {
   builder.hook("build", (build) => {
     // Check dependencies
     if (!build.versions) {
@@ -36,3 +36,7 @@ module.exports = function PgManyToManyPlugin(builder, options) {
   PgManyToManyRelationEdgeColumnsPlugin(builder, options);
   PgManyToManyRelationEdgeTablePlugin(builder, options);
 };
+
+module.exports = PgManyToManyPlugin;
+module.exports.default = PgManyToManyPlugin;
+Object.defineProperty(module.exports, "__esModule", { value: true });
```

This is a similar change to the one in `pg-simplify-inflector`. Confirmed this fixes the issue in my environment.

Happy to make a pull request if desired!

## Environment

- TypeScript 4.8.2
- `allowSyntheticDefaultImports: true`

**Comment by mattbretl** [comment]
Thanks for the report!

I was able to repro this with a `tsc --init` default config plus setting `esModuleInterop: false` (setting `allowSyntheticDefaultImports: true` wasn't sufficient). I'll submit a PR and release a new version.
