### ISSUE TITLE
v5 missing omit smart tag behavior

### ISSUE THREAD

**Issue by smoores-dev** [graphile-contrib/pg-many-to-many#87]
Hopefully I'm not just misunderstanding something about how the new plugin/behavior system works, but it seems like in the `v5` branch, we've lost the ability to filter out relations with the `@omit` smart tag. I was trying this on a project today and couldn't get it to work, and on inspection, I don't see any of the `if (omit(..., "manyToMany"))` checks in `manyToManyRelationships.ts` on the `v5` branch that [exist in `manyToManyRelationships.js` on `master`](https://github.com/graphile-contrib/pg-many-to-many/blob/master/src/manyToManyRelationships.js#L19-L24).

Apologies if this is already on your radar!

**Comment by smoores-dev** [comment]
Aaaand of course, upon trying to implement manyToMany relations _without_ this plugin, I immediately learned that `@omit` is deprecated in favor of `@behavior`, and `@behavior -manyToMany` seems to work as expected!

And even more, I now see that this is actually documented in the README on the `v5` branch 🤦. Sorry for the noise!

**Comment by benjie** [comment]
No worries. Also if you use the V4 preset then @omit continues to work.
